---
title: "Most Probable Names"
author: "Josef Fruehwald"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r}
  library(nameGenerator)
  library(dplyr)
  library(knitr)
```

## Probable Names
```{r}
  eras <- expand.grid(Year = c(1880, 1910, 1950, 1990,2010),
                      Sex = c("M","F"))
```

```{r warning=FALSE}
  eras %>%
    group_by(Year, Sex)%>%
    mutate(name = most_prob_name(Year = Year, Sex = Sex))
```

### Bigrams -> Letter
```{r warning=FALSE}
  eras %>%
    group_by(Year, Sex)%>%
    mutate(name = most_prob_name2(Year = Year, Sex = Sex))
```

## Random Names

Silliness

```{r}
  generate_n_names(30, Year = 2010, Sex = "M")

  generate_n_names(30, Year = 2010, Sex = "F")

  generate_n_names(30, Year = 1910, Sex = "M")

  generate_n_names(30, Year = 1910, Sex = "F")
```

### Bigrams -> Letter
```{r}
  generate_n_names2(30, Year = 2010, Sex = "M")

  generate_n_names2(30, Year = 2010, Sex = "F")

  generate_n_names2(30, Year = 1910, Sex = "M")

  generate_n_names2(30, Year = 1910, Sex = "F")
```
